format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$ruby\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[✗](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[($all_status$ahead_behind)]($style) "
style = "red"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "$"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[ruby]
format = "[$version]($style) "
style = "red"

[nodejs]
format = "[$version]($style) "
style = "green"
